2019-01-21 03:35:24,685 ERROR: Exception on / [GET] [in /home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/linus/flaskApps/microblog/app/routes.py", line 15, in before_request
    db.session.commit()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1008, in commit
    self.transaction.commit()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 487, in commit
    self._prepare_impl()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 466, in _prepare_impl
    self.session.flush()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2424, in flush
    self._flush(objects)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2562, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2522, in _flush
    flush_context.execute()
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 976, in _emit_update_statements
    statement, multiparams
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
    distilled_params,
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/home/linus/flaskApps/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'UPDATE user SET last_seen=? WHERE user.id = ?'] [parameters: ('2019-01-21 11:35:19.647027', 3)] (Background on this error at: http://sqlalche.me/e/e3q8)
2019-01-21 03:40:58,440 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:51]
2019-01-21 03:45:03,712 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:51]
2019-01-24 00:13:36,158 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:78]
2019-02-08 22:36:04,521 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:40:21,805 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:40:26,710 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:40:44,238 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:40:51,544 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:40:57,791 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:42:21,002 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:46:47,400 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:47:21,229 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 22:51:40,000 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:18:13,816 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:18:16,059 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:19:43,414 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:19:59,692 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:20:04,294 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:20:09,938 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:26:57,397 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:28:54,219 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:28:59,634 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:29:02,568 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-08 23:35:48,044 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 00:08:28,905 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 00:19:04,329 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 06:52:04,067 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:46:35,058 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:48:55,886 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:49:20,181 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:52:12,649 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:52:17,672 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:52:20,690 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:52:25,064 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:53:28,055 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:53:33,407 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:53:36,465 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:53:40,265 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:53:44,537 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:54:48,872 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:56:13,365 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 09:56:42,575 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 10:02:43,653 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 10:15:11,217 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
2019-02-09 10:20:41,775 INFO: Microblog startup [in /home/linus/flaskApps/microblog/app/__init__.py:81]
